### ISSUE TITLE
本来就恶心百度网盘，你还让下载百度app扫码登录，你这登录方式看起来是不想要星了

### ISSUE THREAD

**Issue by loooooliiiiikon** [peterq/pan-light#106]

**Comment by MoXiaoXi233** [comment]
不然怎么登陆？靠的就是cookie

**Comment by LgnMs** [comment]
用着免费的还来吐槽，你不服自己fork下来改啊，本来就是开源项目

**Comment by 0756alan** [comment]
保障密码安全。你是有什么大病？

**Comment by yangmeishu** [comment]
啥都不懂还来这逛

**Comment by bearcai** [comment]
恶心百度网盘就别用啊。什么双标沙雕

**Comment by gm100861** [comment]
来, 让我看看你是什么品种的傻逼.

**Comment by loooooliiiiikon** [comment]
@gm100861 跟你爹一样的品种

**Comment by loooooliiiiikon** [comment]
@LgnMs @MoXiaoXi233 @0756alan @yangmeishu @bearcai 这个东西我还真没有用，百毒网盘毕竟不是你说不用就可以完全不用的，领导给你发个百毒网盘链接你能不用？这个东西不能至少不应该只有扫码这一种方式登录，毕竟我都下载百毒软件来扫你登录，我为什么不直接用我下的官方软件下载，最后祝你们全家人生病都去百度~
