### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by liyongjun123** [peterq/pan-light#18]
$ go build  pan-light-pc.go 
 github.com/peterq/pan-light/qt/bindings/widgets
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xe5de56, 0x16)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc0f4000000, 0x4000000, 0x16c9178)
	/usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x16a17c0, 0x2000, 0x16a17d0, 0x1)
	/usr/local/go/src/runtime/malloc.go:633 +0x1cd

ubuntu18.04 + 4G 内存，出现out of memory，大佬有什么办法降低内存占用率吗？
PS：不想增加内存条

**Comment by zaoqi** [comment]
开SWAP。

**Comment by liyongjun123** [comment]
自问自答一下：go build -ldflags "-s -w" pan-light-pc.go
去除debug信息进行编译

**Comment by peterq** [comment]
great you fixed it
