### ISSUE TITLE
你是不是有病啊？

### ISSUE THREAD

**Issue by ikimiler** [peterq/pan-light#28]
公开了交流qq群，申请却要答案，尼玛加一个qq群比登天都难，你玩个锤子啊

**Comment by ikimiler** [comment]
你4不4傻啊

**Comment by ikimiler** [comment]
软件官网 | 在线体验 | 技术文档 | 交流群: 438604465
加群问题：2006年1月2日几点几分？
第一次加：what？立马被拒绝。
第二次加：你怎么这样？也是立马被拒绝。
第三次加：也就是刚刚，weirdo你是不是傻？目前还没审核。
请问weirdo这位管理员，你是几个意思？需要付费进群麻烦就标注一下。

**Comment by peterq** [comment]
@ikimiler, sorry for this
加我qq, 我拉你进去 2638869383
最近比较忙, 我比较少管理群. 因为群到达500成员上限, 但是很多加群的只是普通用户, 并非进来交流技术,  所以为了区分技术用户和普通用户设置了这个问题. golang 开发者知道答案, 因为这是golang中处理日期格式化的模板.

**Comment by ikimiler** [comment]
@peterq  不用了，谢谢

**Comment by songqii** [comment]
看你第一次回答what就知道结果了

**Comment by ikimiler** [comment]
@songqii  我是做java的，他那样的提问我怎么会知道,是一个理性的人，我都申请了三次，怎么样也会通过才对啊，害我以为是要收费才能进群。

**Comment by WuShaoQiang** [comment]
话说那位Java兄弟，一上来就开喷，也是新奇了

**Comment by cexll** [comment]
无脑
