### ISSUE TITLE
下载完成状态错误

### ISSUE THREAD

**Issue by lurenjia528** [peterq/pan-light#4]
![image](https://user-images.githubusercontent.com/37833630/60499577-52170a00-9ceb-11e9-9bf5-c98c4a201ed8.png)

![image](https://user-images.githubusercontent.com/37833630/60499603-5fcc8f80-9ceb-11e9-9e5d-8feb9d3dd6f6.png)

**Comment by peterq** [comment]
这个确定是文件下载完成出现的吗? 还是还没下载完成?

**Comment by peterq** [comment]
and what's your os ? @lurenjia528

**Comment by lurenjia528** [comment]
``` bash
 uname -a 
Linux HT061 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
应该是计算的溢出(int 21亿)了，而且好像下载会丢帧，我下了来2个电影，第二个在没下载完成的时候也变成了-214748.../2.4G

**Comment by peterq** [comment]
已解决 commit: e3c1fe; 确实是范围溢出. golang用的int64, js整数也支持53位. 不过qml的int类型支持正负20亿 https://doc.qt.io/qt-5/qml-int.html

**Comment by lurenjia528** [comment]
等下一个release
安排～

**Comment by lurenjia528** [comment]
这是不是丢帧？

![image](https://user-images.githubusercontent.com/37833630/60571740-ba76f180-9da6-11e9-9d2a-8249add6c8a8.png)

**Comment by peterq** [comment]
图是百度检测到你的并发太大给, 直接把你的连接给断开了, 下载完成的部分会写磁盘, 没下完的部分会丢回队列, 等带重下,不会丢帧 @lurenjia528
