### ISSUE TITLE
文件1.3G居然下载了1.4G 这是什么情况

### ISSUE THREAD

**Issue by Yakumo-Yukari** [peterq/pan-light#47]
![批注 2019-07-20 121015](https://user-images.githubusercontent.com/12076232/61573832-9b3acc80-aae7-11e9-892f-4524c4920380.png)
我这个文件1.3G居然下载了1.4G 这是什么情况 #

**Comment by Eversee22** [comment]
你试试只下一个文件看有没有这种情况
