### ISSUE TITLE
不限速的原理是什么？

### ISSUE THREAD

**Issue by withlin** [peterq/pan-light#5]
rt

**Comment by peterq** [comment]
技术文档里有详细介绍哦:
https://qiniu-cdn.peterq.cn/pan-light/doc/Start/design-pc.html#%E5%B9%B6%E5%8F%91%E4%B8%8B%E8%BD%BD

https://github.com/peterq/pan-light/blob/master/doc/Start/design-pc.md

**Comment by withlin** [comment]
Tks.
