### ISSUE TITLE
又有人在知乎用你的项目骗流量了

### ISSUE THREAD

**Issue by JasonSpeak** [peterq/pan-light#53]
知乎id:苏克1900
回答链接:https://zhuanlan.zhihu.com/p/73452820

**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by Xanthorapedia** [comment]
已经404了，可以考虑close？
