### ISSUE TITLE
这个bug厉害了

### ISSUE THREAD

**Issue by mrdobejelly** [peterq/pan-light#6]
![20190705191859](https://user-images.githubusercontent.com/19746097/60720837-93632000-9f5e-11e9-86d1-169b6f272e31.png)
下载不完！

**Comment by mrdobejelly** [comment]
好了，下载下来的文件只有1.10GB，并且已损坏！

**Comment by zaoqi** [comment]
:+1:

**Comment by jounghu** [comment]
+1

**Comment by zaoqi** [comment]
我为此开了一个PR https://github.com/peterq/pan-light/pull/17

**Comment by peterq** [comment]
这个早已修复了, 请自行编译最新提交, 或等待下一个版本
